name: llm-eti-env
channels:
- conda-forge
- plotly
dependencies:
- python>3.11, <3.14
- streamlit
- openai
- matplotlib
- black
- pandas
- numpy
- seaborn
- python-dotenv
- click
- tqdm
- tabulate
- nbformat
- python-kaleido
- scikit-learn
- statsmodels
- plotly_express
- hdf5
- pip
- pip:
  - stargazer
  - anthropic
  - policyengine
  - policyengine-us